from langchain_google_genai import ChatGoogleGenerativeAI

from app.config import GOOGLE_API_KEY
from app.graph.state import TravelState
from app.tools.flight_tools import search_flights


llm = ChatGoogleGenerativeAI(
    model="gemini-3.5-flash-lite",
    google_api_key=GOOGLE_API_KEY,
    temperature=0.2,
)

llm_with_tools = llm.bind_tools([search_flights])


def flight_agent(state: TravelState):

    prompt = f"""
You are the Flight Agent in a multi-agent AI Travel Planner.

The user wants to travel:

Origin: {state["origin"]}
Origin airport: {state["origin_airport"]}

Destination: {state["destination"]}
Destination airport: {state["destination_airport"]}

Number of travelers: {state["travelers"]}

Departure date: {state["departure_date"]}
Return date: {state["return_date"]}

Your task is to retrieve real flight options.

Use the search_flights tool.

IMPORTANT RULES:

1. Use the exact origin provided by the user.
2. Use the exact destination provided by the user.
3. Use the exact number of travelers.
4. Use the exact departure date.
5. Use the exact return date.
6. Do NOT invent flight information.
7. Do NOT create flight options yourself.
8. Return only data obtained from the flight search tool.
"""

    response = llm_with_tools.invoke(prompt)

    if response.tool_calls:

        tool_call = response.tool_calls[0]

        # Get arguments generated by Gemini
        tool_args = tool_call["args"]

        # Force the correct IATA airport codes
        tool_args["origin"] = state["origin_airport"]
        tool_args["destination"] = state["destination_airport"]

        # Call the real SerpApi flight tool
        tool_result = search_flights.invoke(tool_args)

        return {
            "flight_options": tool_result
        }

    return {
        "flight_options": []
    }
